# Generated by Django 2.1.7 on 2019-03-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_of_transportation', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('meet_need', models.IntegerField(default=0)),
                ('time_spent', models.FloatField()),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(max_length=200, to='events_and_services.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_in_canada', models.IntegerField(default=0)),
                ('housing', models.CharField(max_length=200)),
                ('documment_have', models.IntegerField(default=0)),
                ('children_age', models.IntegerField(default=0)),
                ('current_english', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('work_situation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_and_services.Services'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_and_services.Users'),
        ),
    ]
