# Generated by Django 2.1.7 on 2019-03-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
