# Generated by Django 2.1.7 on 2019-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_services', '0002_users_country_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
